# Generated by Django 5.2.6 on 2025-09-15 05:09

from django.db import migrations
from phonenumbers import parse, is_valid_number, PhoneNumberFormat, format_number

def link_owners_and_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner_name = flat.owner
        owner_phonenumber = flat.owners_phonenumber
        
        # Нормализуем номер телефона
        owner_pure_phone = None
        try:
            parsed_phone = parse(owner_phonenumber, 'RU')
            if is_valid_number(parsed_phone):
                owner_pure_phone = format_number(parsed_phone, PhoneNumberFormat.E164)
        except Exception:
            pass
        
        # Используем get_or_create, чтобы найти или создать собственника
        owner, created = Owner.objects.get_or_create(
            owner_name=owner_name,
            defaults={
                'phonenumber': owner_phonenumber,
                'owner_pure_phone': owner_pure_phone
            }
        )
        

        flat.owners.set([owner])



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(link_owners_and_flats),
    ]